# Generated by Django 4.1.6 on 2023-03-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apimodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='image_uri',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
